[package]
name = "solidhunter"
version = "0.0.1"
edition = "2021"
authors = ["Astrodevs Labs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solc-wrapper = { path = "./solc-wrapper" }
anyhow = "1.0"